FROM ubuntu:focal

# metadata
ARG TARGET=x86_64-linux-musl
ARG OPENSSL_ARCH=linux-x86_64

ENV RUST_MUSL_CROSS_TARGET=$TARGET

WORKDIR /builds

# rustup directory
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH

# install tools and dependencies
RUN set -eux; \
    #sed 's/http:\/\/\(.*\).ubuntu.com\/ubuntu\//[arch-=amd64,i386] http:\/\/ports.ubuntu.com\/ubuntu-ports\//g' /etc/apt/sources.list > /etc/apt/sources.list.d/ports.list \
    #sed -i 's/http:\/\/\(.*\).ubuntu.com\/ubuntu\//[arch=amd64,i386] http:\/\/\1.archive.ubuntu.com\/ubuntu\//g' /etc/apt/sources.list \
    apt update; \
    apt install -y --no-install-recommends \
    autoconf automake binutils ca-certificates cmake file gcc g++ git jq libc6-dev zlib1g-dev \
    libtool m4 make pkg-config curl libssl-dev;

# install musl

RUN curl -sLO https://musl.cc/x86_64-linux-musl-cross.tgz&& \
    tar xzf x86_64-linux-musl-cross.tgz&& \
    cd x86_64-linux-musl-cross&& \
    cp -fR * ../../usr/local/&& \
    cd ..&& rm -rf x86_64-linux-musl-cross*

ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=$TARGET-gcc \
    CC=$TARGET-gcc \
    CXX=$TARGET-g++ \
    CC_x86_64-unknown-linux-gnu=$TARGET-gcc \
    CXX_x86_64-unknown-linux-gnu=$TARGET-g++ \
    CC_x86_64_unknown_linux_musl=$TARGET-gcc \
    CXX_x86_64_unknown_linux_musl=$TARGET-g++\
    TARGET_CC=$TARGET-gcc\
    TARGET_CXX=$TARGET-g++\
    TARGET_AR=$TARGET-ar\
    TARGET_C_INCLUDE_PATH=/usr/local/$TARGET/include/\
    CXX_LIB_PATH_x86_64_unknown_linux_musl=/usr/local/$TARGET/lib/ \
    C_LIB_PATH_x86_64_unknown_linux_musl=/usr/local/$TARGET/lib/\
    CXXSTDLIB=stdc++ \
    TARGET_CXXSTDLIB=stdc++ \
    CXXSTDLIB_x86_64_unknown_linux_musl=stdc++ \
    PATH=/usr/local/x86_64-unknown-linux-musl/bin:$PATH \
    LDFLAGS_x86_64_unknown_linux_gnu=" -static -static-libstdc++ -static-libgcc -L/usr/local/lib -L/usr/local/$TARGET/lib" \
    LDFLAGS_x86_64_unknown_linux_musl=" -static -static-libstdc++ -static-libgcc -L/usr/local/lib -L/usr/local/$TARGET/lib" \
    LDFLAGS=" -static -static-libstdc++ -static-libgcc -L/usr/local/lib -L/usr/local/$TARGET/lib" \
    CFLAGS_x86_64_unknown_linux_gnu=" -fPIC  -I/usr/local/include -I/usr/local/$TARGET/include" \
    CXXFLAGS_x86_64_unknown_linux_gnu=" -fPIC  -I/usr/local/include -I/usr/local/$TARGET/include" \
    CFLAGS_x86_64_unknown_linux_musl=" -fPIC  -I/usr/local/include -I/usr/local/$TARGET/include" \
    CXXFLAGS_x86_64_unknown_linux_musl=" -fPIC  -I/usr/local/include -I/usr/local/$TARGET/include" \
    CFLAGS=" -fPIC  -I/usr/local/include -I/usr/local/$TARGET/include" \
    CXXFLAGS=" -fPIC  -I/usr/local/include -I/usr/local/$TARGET/include" \
    LIBZ_SYS_STATIC=1 \
    LD_LIBRARY_PATH=/usr/local/lib:/usr/local/$TARGET/lib:$LD_LIBRARY_PATH \
    PKG_CONFIG_ALLOW_CROSS=1 \
    PKG_CONFIG_ALL_STATIC=1 \
    OPENSSL_STATIC=1

# Set up a prefix for musl build libraries, make the linker's job of finding them easier

RUN echo "/usr/local/lib" >> /etc/ld-musl-x86_64.path && \
    echo "/usr/local/x86_64-linux-musl/lib" >> /etc/ld-musl-x86_64.path && \
    ln -s /usr/include/x86_64-linux-gnu/asm /usr/local/x86_64-linux-musl/include/asm && \
    ln -s /usr/include/asm-generic /usr/local/x86_64-linux-musl/include/asm-generic && \
    ln -s /usr/include/ /usr/local/x86_64-linux-musl/include

RUN mkdir -p /root/.cargo&&echo "[build]\ntarget = \"$TARGET\"\n\n[target.$TARGET]\nlinker = \"$TARGET-gcc\"\n" > /root/.cargo/config
# OpenSSL
RUN export CC=$TARGET_CC && \
    export C_INCLUDE_PATH=$TARGET_C_INCLUDE_PATH && \
    echo "Building zlib" && \
    VERS=1.2.11 && \
    curl -sLO https://zlib.net/zlib-$VERS.tar.gz && \
    tar xzf zlib-$VERS.tar.gz && cd zlib-$VERS && \
    ./configure --static --archs="-fPIC" --prefix=/usr/local/$TARGET && \
    make && make install && \
    cd .. && rm -rf zlib-$VERS.tar.gz zlib-$VERS checksums.txt && \
    echo "Building OpenSSL" && \
    VERS=1.1.1d && \
    curl -sLO https://www.openssl.org/source/openssl-$VERS.tar.gz && \
    tar xzf openssl-$VERS.tar.gz && cd openssl-$VERS && \
    ./Configure $OPENSSL_ARCH no-async no-afalgeng no-shared no-zlib --static -fPIC --prefix=/usr/local/$TARGET && \
    make depend && \
    make && make install && \
    cd .. && rm -rf openssl-$VERS.tar.gz openssl-$VERS checksums.txt /usr/local/$TARGET/share

# download rustup
ADD "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init" rustup-init

RUN	chmod +x rustup-init; \
  ./rustup-init -y --no-modify-path --default-toolchain stable; \
  rm rustup-init; \
  chmod -R a+w $RUSTUP_HOME $CARGO_HOME; \
  rustup install nightly; \
# install x86_64_unknown_linux_musl toolchain
	rustup target add x86_64_unknown_linux_musl; \
	rustup target add x86_64_unknown_linux_musl --toolchain nightly; \
  SCCACHE_LATEST_URL=`curl -sL    https://api.github.com/repos/mozilla/sccache/releases/latest | jq -r '.assets[2].browser_download_url'`; \
  curl -L $SCCACHE_LATEST_URL | tar zxf - --overwrite --strip-components=1 -C /usr/local/cargo/bin ; \
  rm -rf /usr/local/rustup/toolchains/*/share; \
  rm -rf $CARGO_HOME/registry/*; \
# apt clean up
  apt autoremove -y; \
  apt clean; \
  rm -rf /var/lib/apt/lists/*;

#COPY config/config /root/.cargo/$TARGET-config
ENV OPENSSL_DIR=/usr/local/musl/$TARGET/ \
    OPENSSL_INCLUDE_DIR=/usr/local/$TARGET/include/ \
    DEP_OPENSSL_INCLUDE=/usr/local/$TARGET/include/ \
    OPENSSL_LIB_DIR=/usr/local/$TARGET/lib/ \
    PORTABLE=1
RUN mkdir $HOME/sccache
ENV RUST_BACKTRACE=full\
    RUSTC_WRAPPER=sccache \
    SCCACHE_DIR=$HOME/sccache \
    SCCACHE_CACHE_SIZE=1G
