name: Build Clang

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Build Clang MUSL toolchain
        run: |
          docker run generalbeck/docker-cross-rust:alpine-sccache /bin/sh -c \
          'git clone https://github.com/General-Beck/docker-cross-rust.git clang&& \
          cd clang && git checkout ngtc && cd dockerfiles && ls -a && \
          sh sync.sh release/9.x && sh configure.sh && sh build.sh && sh install.sh' \
          ls -a
