name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file dockerfiles/Dockerfile.x86_64-unknown-linux-musl --tag ghcr.io/general-beck/docker-cross-rust/docker-cross-rust:x86_64-unknown-linux-musl
      - name: Docker login
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Push the Docker image
        run: docker push ghcr.io/general-beck/docker-cross-rust/docker-cross-rust:x86_64-unknown-linux-musl
      - name: Docker logout
        run: docker logout
